import jsPDF from "jspdf";

interface ExportNoteOptions {
  title: string;
  content: string;
  createdAt: Date;
  updatedAt: Date;
}

export const exportNoteToPdf = async ({ title, content, createdAt, updatedAt }: ExportNoteOptions) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = margin;

  // Header
  doc.setFillColor(34, 40, 49); // Dark background
  doc.rect(0, 0, pageWidth, 40, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(title, margin, yPosition + 10);

  // Metadata
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(180, 180, 180);
  doc.text(`Created: ${createdAt.toLocaleString()}`, margin, yPosition + 20);
  doc.text(`Modified: ${updatedAt.toLocaleString()}`, margin, yPosition + 26);

  yPosition = 50;

  // Content
  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);

  // Split content into lines that fit the page width
  const lines = doc.splitTextToSize(content, contentWidth);
  const lineHeight = 5;

  for (let i = 0; i < lines.length; i++) {
    // Check if we need a new page
    if (yPosition + lineHeight > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      
      // Add header to new page
      doc.setFillColor(34, 40, 49);
      doc.rect(0, 0, pageWidth, 15, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(180, 180, 180);
      doc.text(title, margin, 10);
      doc.text(`Page ${doc.internal.pages.length - 1}`, pageWidth - margin - 15, 10);
      
      yPosition = 25;
      doc.setFont("courier", "normal");
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
    }

    // Handle markdown-like headers
    const line = lines[i];
    if (line.startsWith("# ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(30, 30, 30);
      doc.text(line.substring(2), margin, yPosition);
      yPosition += lineHeight + 3;
    } else if (line.startsWith("## ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(40, 40, 40);
      doc.text(line.substring(3), margin, yPosition);
      yPosition += lineHeight + 2;
    } else if (line.startsWith("### ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      doc.text(line.substring(4), margin, yPosition);
      yPosition += lineHeight + 1;
    } else if (line.startsWith("---")) {
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
      yPosition += lineHeight;
    } else {
      doc.setFont("courier", "normal");
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      doc.text(line, margin, yPosition);
      yPosition += lineHeight;
    }
  }

  // Footer on last page
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by Cyberellum Lab Notebook • ${new Date().toLocaleString()}`,
    margin,
    pageHeight - 10
  );

  // Save the PDF
  const sanitizedTitle = title.replace(/[^a-z0-9]/gi, "_").substring(0, 50);
  doc.save(`${sanitizedTitle}_${new Date().toISOString().split("T")[0]}.pdf`);
};
