project_id = "wymznknyhbsiqycrsduj"

[functions.research-assistant]
verify_jwt = false

[functions.nutrigenomics-forecast]
verify_jwt = false

[functions.send-nutrigenomics-report]
verify_jwt = false

[functions.federated-query]
verify_jwt = false