server {
  listen 80;
  server_name genomic.axiom-x.us www.genomic.axiom-x.us;
  client_max_body_size 100m;

  location /api/ {
    proxy_pass http://127.0.0.1:8100/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    root /opt/dna-me/current;
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 443 ssl;
  server_name genomic.axiom-x.us www.genomic.axiom-x.us;
  client_max_body_size 100m;

  ssl_certificate /etc/nginx/ssl/cyber-medi-origin.crt;
  ssl_certificate_key /etc/nginx/ssl/cyber-medi-origin.key;

  location /api/ {
    proxy_pass http://127.0.0.1:8100/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }

  location / {
    root /opt/dna-me/current;
    try_files $uri $uri/ /index.html;
  }
}
